baseURL = "https://namith.agilifylabs.in/"
languageCode = "en-us"
title = "Namith Scindhia"

[build]
  [build.buildStats]
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false

[params]
  description = "Forward Deployed Engineer"
